# Generated by Django 3.2.25 on 2025-03-22 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0002_auto_20250318_0651'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='Email',
            new_name='email',
        ),
    ]
