# Generated by Django 3.2.25 on 2025-03-22 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='PG',
            new_name='High_school',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='UG',
            new_name='Post_graduate',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='XIIth',
            new_name='Primary_school',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Xth',
            new_name='Under_graduate',
        ),
    ]
